name: Run mechanical layer tests, and remaining pre-commit hooks

on:
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm clang build-essential cmake graphviz

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install llvm graphviz

      - name: Add LLVM to PATH (macOS)
        if: runner.os == 'macOS'
        run: | # Add Homebrew LLVM bin directory to PATH for clang-tidy
          echo "$(brew --prefix llvm)/bin" >> $GITHUB_PATH

      - name: Set SDKROOT for clang/clang-tidy
        if: runner.os == 'macOS'
        run: |
          echo "SDKROOT=$(xcrun --show-sdk-path)" >> "$GITHUB_ENV"

      - name: Install Doxygen
        uses: ssciwr/doxygen-install@v1
        with:
          version: "1.13.2"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync

      - name: Build the C++ project
        run: |
          cd src/mechanical_layer
          cmake -S . -B build -DBUILD_SHARED_LIBS=ON
          cmake --build build
          cd ../..

      - name: Run copyright check pre-commit hook
        run: |
          uv run pre-commit run check-copyright --all-files

      - name: Run clang-tidy pre-commit hook
        run: |
          uv run pre-commit run clang-tidy --all-files

      - name: Run pytest pre-commit hook for the configuration tests
        run: |
          uv run pre-commit run uv-pytest --all-files

      - name: Run notebooks tests pre-commit hook
        if: runner.os == 'macOS'
        run: |
          uv run ./.check-notebooks.sh

      - name: Run doxygen pre-commit hook
        run: |
          uv run pre-commit run check-doxygen --all-files

      - name: Run the mechanical layer tests
        run: |
          cd ./tests/mechanical_layer
          ./run_mechanical_tests.sh
          cd ../..
