name: Run mechanical layer tests and C++ checks

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}

    env:
      FFMPEG_BIN: /usr/bin/ffmpeg

    steps:
      - uses: actions/checkout@v3

      - name: Install ffmpeg (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install ffmpeg (macOS)
        if: runner.os == 'macOS'
        run: brew install ffmpeg

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync --extra dev

      - name: Build the C++ project
        run: |
          cd src/mechanical_layer
          cmake -H. -Bbuild -DBUILD_SHARED_LIBS=ON
          cmake --build build
          cd ../..

      - name: Install pre-commit
        run: uv run pre-commit install

      - name: Run pre-commit hooks
        run: uv run pre-commit run --all-files

      # - name: Run the mechanical layer tests
      #   run: |
      #     cd ./tests/mechanical_layer
      #     ./run_mechanical_tests
      #     cd ../..
